### ISSUE TITLE
Bug: I am getting Error: Error signing manifest: Token could not be parsed 

### ISSUE THREAD

**Issue by jagadeesh-kancherla-tfs** [grafana/plugin-tools#288]
### Which package(s) does this bug affect?

- [ ] Create Plugin
- [X] Sign Plugin

### Package versions

```shell
npx @grafana/sign-plugin@latest --rootUrls xxxxxxxxx
Need to install the following packages:
  @grafana/sign-plugin@latest
Ok to proceed? (y) y
Building manifest...
Signing manifest...
Error: Error signing manifest: Token could not be parsed
    at /root/.npm/_npx/4e038a744f1b0d34/node_modules/@grafana/sign-plugin/dist/utils/manifest.js:241:31
    at step (/root/.npm/_npx/4e038a744f1b0d34/node_modules/@grafana/sign-plugin/dist/utils/manifest.js:33:23)
    at Object.throw (/root/.npm/_npx/4e038a744f1b0d34/node_modules/@grafana/sign-plugin/dist/utils/manifest.js:14:53)
    at rejected (/root/.npm/_npx/4e038a744f1b0d34/node_modules/@grafana/sign-plugin/dist/utils/manifest.js:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### What happened?

npx @grafana/sign-plugin@latest --rootUrls xxxxxxxxx
Need to install the following packages:
  @grafana/sign-plugin@latest
Ok to proceed? (y) y
Building manifest...
Signing manifest...
Error: Error signing manifest: Token could not be parsed
    at /root/.npm/_npx/4e038a744f1b0d34/node_modules/@grafana/sign-plugin/dist/utils/manifest.js:241:31
    at step (/root/.npm/_npx/4e038a744f1b0d34/node_modules/@grafana/sign-plugin/dist/utils/manifest.js:33:23)
    at Object.throw (/root/.npm/_npx/4e038a744f1b0d34/node_modules/@grafana/sign-plugin/dist/utils/manifest.js:14:53)
    at rejected (/root/.npm/_npx/4e038a744f1b0d34/node_modules/@grafana/sign-plugin/dist/utils/manifest.js:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

### What you expected to happen

I was trying to sign the Opsramp plugin https://docs.opsramp.com/integrations/applications/grafana/

### How to reproduce it (as minimally and precisely as possible)

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

```shell
System:
    OS: Linux 5.4 Amazon Linux 2
    CPU: (4) x64 AMD EPYC 7R13 Processor
    Memory: 24.07 GB / 30.69 GB
    Container: Yes
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 17.9.1 - ~/.nvm/versions/node/v17.9.1/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v17.9.1/bin/npm
```

**Comment by tolzhabayev** [comment]
@jagadeesh-kancherla-tfs it feels like the API Key you are using is not correct?

It should be available in the environment variable called `GRAFANA_API_KEY` https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/#sign-a-private-plugin
