### ISSUE TITLE
Bug: Running `yarn create @grafana/plugin update` fails

### ISSUE THREAD

**Issue by zoltanbedi** [grafana/plugin-tools#643]
### Which package(s) does this bug affect?

- [X] Create Plugin
- [ ] Sign Plugin

### Package versions

```shell
I don't know as running that command also fails.
```

### What happened?

```
yarn create @grafana/plugin update
➤ YN0000: · Yarn 4.0.0
➤ YN0000: ┌ Resolution step
➤ YN0085: │ + @grafana/create-plugin@npm:2.10.1, @babel/runtime-corejs3@npm:7.23.7, @colors/colors@npm:1.5.0, and 291 more.
➤ YN0000: └ Completed in 4s 829ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ 163 packages were added to the project (+ 6.6 MiB).
➤ YN0000: └ Completed in 2s 156ms
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0007: │ core-js-pure@npm:3.35.0 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 0s 977ms
➤ YN0000: · Done with warnings in 7s 995ms

/private/var/folders/6l/53p9b6gd37g00g051_4g92r80000gn/T/xfs-f832e11f/dlx-61128/.pnp.cjs:8529
      Error.captureStackTrace(firstError);
            ^

Error: @grafana/create-plugin tried to access minimist, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: minimist
Required by: @grafana/create-plugin@npm:2.10.1 (via /Users/zoltanbedi/.yarn/berry/cache/@grafana-create-plugin-npm-2.10.1-7b01e92586-10.zip/node_modules/@grafana/create-plugin/dist/bin/)

Require stack:
- /Users/zoltanbedi/.yarn/berry/cache/@grafana-create-plugin-npm-2.10.1-7b01e92586-10.zip/node_modules/@grafana/create-plugin/dist/bin/run.js
    at require$$0.Module._resolveFilename (/private/var/folders/6l/53p9b6gd37g00g051_4g92r80000gn/T/xfs-f832e11f/dlx-61128/.pnp.cjs:8529:13)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at require$$0.Module._load (/private/var/folders/6l/53p9b6gd37g00g051_4g92r80000gn/T/xfs-f832e11f/dlx-61128/.pnp.cjs:8420:31)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/Users/zoltanbedi/.yarn/berry/cache/@grafana-create-plugin-npm-2.10.1-7b01e92586-10.zip/node_modules/@grafana/create-plugin/dist/bin/run.js:7:34)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at require$$0.Module._extensions..js (/private/var/folders/6l/53p9b6gd37g00g051_4g92r80000gn/T/xfs-f832e11f/dlx-61128/.pnp.cjs:8572:33)
    at Module.load (node:internal/modules/cjs/loader:1091:32)

Node.js v20.9.0
```

### What you expected to happen

it should work

### How to reproduce it (as minimally and precisely as possible)

run the command

### Environment

```shell
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M2
    Memory: 249.59 MB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    Yarn: 4.0.0 - ~/.nvm/versions/node/v20.9.0/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
  Browsers:
    Chrome: 120.0.6099.199
    Safari: 17.2.1
```

**Comment by zoltanbedi** [comment]
It turned out to be a problem in my environment. under my user in max there is a .config/yarn/global folder which contains the globally called modules like create-plugin. In this folder there is a yarn.lock file as well. Once I recreated the yarn.lock file the error went away.
